name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main   # altere se for outra branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - id: set_base
        name: Determine BASE_HREF
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY%%/*}"
          if [ "${REPO_NAME}" = "${OWNER}.github.io" ]; then
            BASE_HREF="/"
          else
            BASE_HREF="/${REPO_NAME}/"
          fi
          echo "base_href=${BASE_HREF}" >> $GITHUB_OUTPUT

      - name: Build Flutter web
        run: flutter build web --release --base-href "${{ steps.set_base.outputs.base_href }}"

      - name: SPA fallback (copy index to 404)
        run: cp build/web/index.html build/web/404.html

      # Opcional: criar CNAME quando usar domínio personalizado
      # - name: Create CNAME
      #   run: echo 'www.seu-dominio.com' > build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
